import React from 'react';
import './global.css';
import { Metadata } from 'next';
import { ToastContainer } from 'react-toastify';
import { Paper, ThemeProvider } from '@mui/material';
import theme from '../themes/default';

export const metadata: Metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={theme}>
          <ToastContainer />

          <Paper
            sx={{
              display: 'flex',
              flexDirection: 'column',
              padding: '24px',
              margin: '0 auto',
              maxWidth: '1200px',
              minHeight: '100dvh',
            }}
          >
            {children}
          </Paper>
        </ThemeProvider>
      </body>
    </html>
  );
}
